# Generated by Django 5.0.6 on 2024-07-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='asignada',
            field=models.BooleanField(default=False),
        ),
    ]
