# Generated by Django 5.0.6 on 2024-07-09 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_usuario_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
    ]
